import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Incident, Alert, MetricsSummary } from './types';
import { formatTimestamp } from './metrics';

export interface ReportOptions {
  includeMetrics?: boolean;
  includeAlerts?: boolean;
  includeAISuggestions?: boolean;
  dateRange?: {
    start: number;
    end: number;
  };
}

export function exportIncidentToPDF(incident: Incident) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(26, 35, 50);
  doc.text('Incident Report', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text('Generated by LLM Guardian', pageWidth / 2, yPos, { align: 'center' });
  doc.text(`Report Date: ${new Date().toLocaleString()}`, pageWidth / 2, yPos + 5, { align: 'center' });
  yPos += 20;

  doc.setDrawColor(229, 231, 235);
  doc.line(20, yPos, pageWidth - 20, yPos);
  yPos += 10;

  // Incident Details
  doc.setFontSize(16);
  doc.setTextColor(26, 35, 50);
  doc.text('Incident Details', 20, yPos);
  yPos += 10;

  const details = [
    ['Incident ID', incident.id],
    ['Title', incident.title],
    ['Severity', incident.severity.toUpperCase()],
    ['Status', incident.status.toUpperCase()],
    ['Created At', formatTimestamp(incident.createdAt)],
    ['Description', incident.description]
  ];

  if (incident.resolvedAt) {
    details.push(['Resolved At', formatTimestamp(incident.resolvedAt)]);
    const duration = incident.resolvedAt - incident.createdAt;
    const hours = Math.floor(duration / (1000 * 60 * 60));
    const minutes = Math.floor((duration % (1000 * 60 * 60)) / (1000 * 60));
    details.push(['Duration', `${hours}h ${minutes}m`]);
  }

  autoTable(doc, {
    startY: yPos,
    head: [],
    body: details,
    theme: 'plain',
    styles: {
      fontSize: 10,
      cellPadding: 4
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 40, textColor: [107, 114, 128] },
      1: { cellWidth: 'auto', textColor: [26, 35, 50] }
    }
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // AI Suggestions
  if (incident.aiSuggestion) {
    doc.setFontSize(14);
    doc.setTextColor(26, 35, 50);
    doc.text('AI Recommendation', 20, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99);
    const splitText = doc.splitTextToSize(incident.aiSuggestion, pageWidth - 40);
    doc.text(splitText, 20, yPos);
    yPos += splitText.length * 5 + 10;
  }

  // Associated Alerts
  if (incident.alerts && incident.alerts.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(26, 35, 50);
    doc.text(`Associated Alerts (${incident.alerts.length})`, 20, yPos);
    yPos += 8;

    const alertData = incident.alerts.map(alert => [
      formatTimestamp(alert.timestamp),
      alert.ruleName,
      alert.severity.toUpperCase(),
      alert.message,
      alert.acknowledged ? 'Yes' : 'No'
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Timestamp', 'Rule', 'Severity', 'Message', 'Acknowledged']],
      body: alertData,
      theme: 'striped',
      headStyles: {
        fillColor: [77, 140, 255],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      styles: {
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 40 },
        2: { cellWidth: 25 },
        3: { cellWidth: 'auto' },
        4: { cellWidth: 25 }
      }
    });
  }

  yPos = (doc as any).lastAutoTable.finalY + 10;

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text('Powered by Google Cloud • Vertex AI • LLM Guardian', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  const filename = `incident-${incident.id}-${Date.now()}.pdf`;
  doc.save(filename);
}

export function exportIncidentsReportToPDF(
  incidents: Incident[],
  summary: MetricsSummary,
  options: ReportOptions = {}
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(26, 35, 50);
  doc.text('LLM Guardian', pageWidth / 2, yPos, { align: 'center' });
  yPos += 8;

  doc.setFontSize(16);
  doc.text('Observability Report', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, yPos, { align: 'center' });
  
  if (options.dateRange) {
    yPos += 5;
    const start = new Date(options.dateRange.start).toLocaleString();
    const end = new Date(options.dateRange.end).toLocaleString();
    doc.text(`Period: ${start} - ${end}`, pageWidth / 2, yPos, { align: 'center' });
  }
  yPos += 15;

  doc.setDrawColor(229, 231, 235);
  doc.line(20, yPos, pageWidth - 20, yPos);
  yPos += 12;

  // Executive Summary
  doc.setFontSize(16);
  doc.setTextColor(26, 35, 50);
  doc.text('Executive Summary', 20, yPos);
  yPos += 10;

  if (options.includeMetrics) {
    const metricsData = [
      ['Total Requests', summary.totalRequests.toLocaleString()],
      ['Average Latency', `${summary.avgLatency.toFixed(0)}ms`],
      ['P95 Latency', `${summary.p95Latency.toFixed(0)}ms`],
      ['P99 Latency', `${summary.p99Latency.toFixed(0)}ms`],
      ['Error Rate', `${summary.errorRate.toFixed(2)}%`],
      ['Total Cost', `$${summary.totalCost.toFixed(4)}`],
      ['Total Tokens', summary.totalTokens.toLocaleString()]
    ];

    autoTable(doc, {
      startY: yPos,
      head: [],
      body: metricsData,
      theme: 'plain',
      styles: {
        fontSize: 10,
        cellPadding: 4
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50, textColor: [107, 114, 128] },
        1: { cellWidth: 'auto', textColor: [26, 35, 50], halign: 'right' }
      }
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  const openIncidents = incidents.filter(i => i.status !== 'resolved');
  const resolvedIncidents = incidents.filter(i => i.status === 'resolved');
  const criticalIncidents = incidents.filter(i => i.severity === 'critical');

  const statusData = [
    ['Total Incidents', incidents.length.toString()],
    ['Open', openIncidents.length.toString()],
    ['Resolved', resolvedIncidents.length.toString()],
    ['Critical Severity', criticalIncidents.length.toString()]
  ];

  autoTable(doc, {
    startY: yPos,
    head: [],
    body: statusData,
    theme: 'plain',
    styles: {
      fontSize: 10,
      cellPadding: 4
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50, textColor: [107, 114, 128] },
      1: { cellWidth: 'auto', textColor: [26, 35, 50], halign: 'right' }
    }
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Incidents List
  if (incidents.length > 0) {
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(16);
    doc.setTextColor(26, 35, 50);
    doc.text('Incidents Overview', 20, yPos);
    yPos += 8;

    const incidentData = incidents.map(incident => {
      const duration = incident.resolvedAt 
        ? `${Math.floor((incident.resolvedAt - incident.createdAt) / (1000 * 60))}m`
        : 'Ongoing';
      
      return [
        incident.id.substring(0, 15) + '...',
        incident.title,
        incident.severity.toUpperCase(),
        incident.status.toUpperCase(),
        formatTimestamp(incident.createdAt),
        duration
      ];
    });

    autoTable(doc, {
      startY: yPos,
      head: [['ID', 'Title', 'Severity', 'Status', 'Created', 'Duration']],
      body: incidentData,
      theme: 'striped',
      headStyles: {
        fillColor: [77, 140, 255],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      styles: {
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 30, fontSize: 7 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 20 },
        3: { cellWidth: 25 },
        4: { cellWidth: 30 },
        5: { cellWidth: 20 }
      }
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;
  }

  // AI Suggestions Section
  if (options.includeAISuggestions && incidents.some(i => i.aiSuggestion)) {
    if (yPos > 200) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(16);
    doc.setTextColor(26, 35, 50);
    doc.text('AI Recommendations', 20, yPos);
    yPos += 8;

    incidents.forEach(incident => {
      if (incident.aiSuggestion) {
        if (yPos > 260) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(11);
        doc.setTextColor(26, 35, 50);
        doc.setFont('helvetica', 'bold');
        doc.text(incident.title, 20, yPos);
        doc.setFont('helvetica', 'normal');
        yPos += 6;

        doc.setFontSize(9);
        doc.setTextColor(75, 85, 99);
        const splitText = doc.splitTextToSize(incident.aiSuggestion, pageWidth - 40);
        doc.text(splitText, 20, yPos);
        yPos += splitText.length * 4 + 8;
      }
    });
  }

  // Page Numbers
  const totalPages = (doc.internal as any).pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - 20,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
    doc.text(
      'Powered by Google Cloud • Vertex AI • LLM Guardian',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  const filename = `llm-guardian-report-${Date.now()}.pdf`;
  doc.save(filename);
}

export function exportAlertsToPDF(alerts: Alert[]) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  doc.setFontSize(20);
  doc.setTextColor(26, 35, 50);
  doc.text('Alerts Report', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, yPos, { align: 'center' });
  doc.text(`Total Alerts: ${alerts.length}`, pageWidth / 2, yPos + 5, { align: 'center' });
  yPos += 20;

  doc.setDrawColor(229, 231, 235);
  doc.line(20, yPos, pageWidth - 20, yPos);
  yPos += 10;

  const unacknowledged = alerts.filter(a => !a.acknowledged).length;
  const critical = alerts.filter(a => a.severity === 'critical').length;
  const warning = alerts.filter(a => a.severity === 'warning').length;

  const summaryData = [
    ['Unacknowledged', unacknowledged.toString()],
    ['Critical', critical.toString()],
    ['Warning', warning.toString()],
    ['Info', (alerts.length - critical - warning).toString()]
  ];

  autoTable(doc, {
    startY: yPos,
    head: [],
    body: summaryData,
    theme: 'plain',
    styles: {
      fontSize: 10,
      cellPadding: 4
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50, textColor: [107, 114, 128] },
      1: { cellWidth: 'auto', textColor: [26, 35, 50], halign: 'right' }
    }
  });

  yPos = (doc as any).lastAutoTable.finalY + 15;

  if (alerts.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(26, 35, 50);
    doc.text('Alert Details', 20, yPos);
    yPos += 8;

    const alertData = alerts.map(alert => [
      formatTimestamp(alert.timestamp),
      alert.ruleName,
      alert.severity.toUpperCase(),
      alert.message,
      alert.value.toString(),
      alert.acknowledged ? 'Yes' : 'No'
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Timestamp', 'Rule', 'Severity', 'Message', 'Value', 'Ack']],
      body: alertData,
      theme: 'striped',
      headStyles: {
        fillColor: [77, 140, 255],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9
      },
      styles: {
        fontSize: 8,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 32 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 22 },
        3: { cellWidth: 50 },
        4: { cellWidth: 18 },
        5: { cellWidth: 15 }
      }
    });
  }

  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text('Powered by Google Cloud • Vertex AI • LLM Guardian', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  const filename = `alerts-report-${Date.now()}.pdf`;
  doc.save(filename);
}
